#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# pour avoir les binaires installé via pear
if (( $+commands[brew] )); then
  export PATH="$(brew --prefix php53)/bin:$PATH"

  # Formula coreutils
  # Pour avoir les commandes GNU plutôt que les vieillotes d'OSX
  #PATH="$(brew --prefix coreutils)/libexec/gnubin:$PATH"

  # Et avoir les bons manuels
  #MANPATH="$(brew --prefix coreutils)/libexec/gnuman:$MANPATH"
fi

# MacVim aliases
alias mvimr='mvim --remote-silent'

# Souvent à modifier
alias vimrc='vim ~/.vimrc'
alias gvimrc='vim ~/.gvimrc'
alias zshrc='vim ~/.zshrc'
alias sozsh='source ~/.zshrc'

# ls commands
alias ls++='LC_ALL=en_US.UTF-8 LANG=en ls++'
alias lsd='ls -ld .*' # List only dot files

# modified commands
alias ping='ping -c 5'
alias mysql='mysql -u root -p'

# shortcut
alias q='exit'
alias c='clear'
alias wee='weechat-curses'
alias tree='nocorrect tree'

# DA2I
alias jd='javadoc -d doc sources/*java'
alias jc='javac -sourcepath sources/ -d classes/ -classpath classes/ sources/*.java'
alias jex='java -classpath classes'
alias jdir='mkdir classes doc sources'
alias gvim='gvim --remote-silent'

if [[ "$OSTYPE" == linux-gnu ]]; then

  # Mes binaires avant les autres
  export PATH="$HOME/bin:$PATH"

  # Activer fasd
  eval "$(fasd --init auto)"

  # Redémarre le serveur tomcat
  alias tomreload='$HOME/tomcat/bin/startup.sh && $HOME/tomcat/bin/shutdown.sh'

  # Avoir les commandes java
  export JAVA_HOME="/usr/lib/jvm/java-6-sun"
  export PATH=$PATH:"$JAVA_HOME/bin"

  # Sourcing des classes pour la compilation J2E
  export CLASSPATH=".:..:$HOME/Documents/da2i/bddr/driver/driver_postgresql.jar"
  export CLASSPATH="$CLASSPATH:$HOME/tomcat/lib/servlet-api.jar"

fi
