#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Set the list of directories that Zsh searches for programs.
path=(
  $HOME/bin
  $HOME/.gem/ruby/2.0.0/bin
  /usr/lib/ruby/gems/2.0.0/bin
  /usr/local/{bin,sbin}
  $path
)

# Customize to your needs...

# files...
alias vimrc='e ~/.vimrc'
alias gvimrc='e ~/.gvimrc'
alias zshrc='e ~/.zshrc'
alias sozsh='source ~/.zshrc'
alias zshenv='e ~/.zshenv'
alias zpreztorc='e ~/.zpreztorc'
alias gitconfig='e ~/.gitconfig'
alias tmuxconf='e ~/.tmux.conf'

# ls commands
alias lsd='ls -ld .*' # List only dot files

# shortcut
alias q='exit'
alias c='clear'
alias wee='weechat-curses'

# Activer fasd
eval "$(fasd --init auto)"

# RVM (vimgolf)
# Load RVM into a shell session *as a function*
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

# vide les fichiers en paramètre de la commande
function vider_fichiers { for file in $@; do :>! $file ; done }

# filtre la ligne de recherche grep de ps
function psgrep { ps axuf | grep -v grep | grep "$@" -i --color=auto; }
